version: '3.4'

services:
  appclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  blog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

